### PR TITLE
Changed all manual scrobble pulls to be threaded and async

### PR DESCRIPTION
**Pull request by kbuffington**
- Keeping API calls to every 200ms to stay at last.fm API rate limts
 - added thread safety for writing to indexdb
 - queueing hashes and refreshing every 25 completed
 - mutex to prevent more than one concurent manual scrobble pull

### CODE REVIEW

**Comment by kbuffington** [comment]
@marc2k3 Could you take a look at this for me? Thread safety and mutexes (let alone C++) aren't really my area of expertise and I want to make sure I'm not missing something obvious before I put out a beta. It appears to be working well right now in all my tests though.

**Comment by marc2k3** [comment]
Sorry but I have no clue at all. I'm barely know what I'm doing with javascript let alone C++. I've never had any idea what I'm doing. Remember I broke your colour scheme function without even realising it. I'm just an enthusiastic copy/paster!!

**Comment by kbuffington** [comment]
Haha, that's astounding to me. Maybe it's just @TheQwertiest who knows wtf he's doing!

Thanks for the tip on main_thread_callback. Think I've got it working correctly using `fb2k::inMainThread` now. I just need to figure out how to rebuild my project again now 🙄

**Comment by marc2k3** [comment]
I just cloned your repo and compiled it works just fine with VS2019, v142 toolset and latest fb2k SDK. 

```
6>   Creating library Z:\Git\SDK-2019-06-17\foobar2000\foo_enhanced_playcount\Release\foo_enhanced_playcount.lib and object Z:\Git\SDK-2019-06-17\foobar2000\foo_enhanced_playcount\Release\foo_enhanced_playcount.exp
6>Generating code
6>Previous IPDB not found, fall back to full compilation.
6>All 4006 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
6>Finished generating code
6>foo_enhanced_playcount.vcxproj -> Z:\Git\SDK-2019-06-17\foobar2000\foo_enhanced_playcount\Release\foo_enhanced_playcount.dll
6>Done building project "foo_enhanced_playcount.vcxproj".
```

I had to add my wtl folder as includes in both your project and ATL helpers.

**Comment by marc2k3** [comment]
Regarding compilation issues with WTL10, have you tried the latest from the git master? That's what I used and works.

`git clone https://git.code.sf.net/p/wtl/git wtl-git`

**Comment by kbuffington** [comment]
I was using 10.0.9163 which appears to be the latest release.

**Comment by marc2k3** [comment]
Well it looks like Peter found something to fix - there is an update:

http://foobar2000.org/SDK

**Pull request merged**
